//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Song
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Song()
        {
            this.Album = new HashSet<Album>();
            this.Producer = new HashSet<Producer>();
            this.RecordingStudio = new HashSet<RecordingStudio>();
            this.Singer = new HashSet<Singer>();
            this.SongWriter = new HashSet<SongWriter>();
        }
    
        public int ID { get; set; }
        public int BeatsPerMinute { get; set; }
        public string Genre { get; set; }
        public string IsInColor { get; set; }
        public string Label { get; set; }
        public string Language { get; set; }
        public int LengthInSeconds { get; set; }
        public double Rating { get; set; }
        public System.DateTime ReleaseDate { get; set; }
        public string SingersName { get; set; }
        public string Subtitle { get; set; }
        public string Title { get; set; }
        public int YearRecorded { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Album> Album { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Producer> Producer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordingStudio> RecordingStudio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Singer> Singer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SongWriter> SongWriter { get; set; }
    }
}
